version: '{build}'
image: Visual Studio 2015
platform:
  -x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    PYTHONWARNINGS: ignore:DEPRECATION
    MSSdk: 1
install:
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\..\..\VC\vcvarsall.bat" x64'
  - ps: C:\Python38-x64\python.exe -m pip install setuptools wheel
build_script:
  - ps: |
      cd solnp
      C:\Python38-x64\python.exe setup.py sdist bdist_wheel
      pip install ./
      cd ..
artifacts:
  - path: cpp_sonlp\dist\*.whl
    name: wheels