version: '{build}'
image: Visual Studio 2015
environment:
  global:
    DISTUTILS_USE_SDK: 1
    PYTHONWARNINGS: ignore:DEPRECATION
    MSSdk: 1
install:
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - ps: C:\Python38-x64\bin\python.exe -m pip install --disable-pip-version-check --user --upgrade pip setuptools wheel
build_script:
  - ps: |
      cd cpp_sonlp
      C:\Python38-x64\bin\python.exe setup.py sdist bdist_wheel
      pip install ./
      cd ..
artifacts:
  - path: cpp_sonlp\dist\*.whl
    name: wheels