version: '{build}'
image: Visual Studio 2015
platform:
  - x86
  - x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    PYTHONWARNINGS: ignore:DEPRECATION
    MSSdk: 1
  matrix:
    - PYTHON: 27
#    - PYTHON: 36
#    - CONDA: 27
#    - CONDA: 36
install:
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - ps: |
      if ($env:PYTHON) {
        if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
#        $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
        C:\Python$env:PYTHON\bin\pip install --disable-pip-version-check --user --upgrade pip setuptools wheel
      } elseif ($env:CONDA) {
        if ($env:CONDA -eq "27") { $env:CONDA = "" }
        if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
        $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda update -q conda
        conda install -q conda-build
      }
build_script:
  - ps: |
      if ($env:PYTHON) {
        cd cpp_sonlp
        C:\Python$env:PYTHON\bin\python setup.py sdist bdist_wheel
        cd ..
        pip install ./
      } else {
        echo "conda build conda.recipe"
        conda build conda.recipe
        echo "conda install --use-local pysolnp"
        conda install --use-local pysolnp
      }
#test_script:
#  - ps: python python_solnp\test\test.py
#artifacts:
#  - path: cpp_sonlp\dist\*.whl
#    name: wheels