notifications:
  email: false

if: tag IS present
matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    - sudo: required
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
        - PRE_CMD=linux32
install:
  - docker pull $DOCKER_IMAGE
script:
  - docker run --rm -v `pwd`:/io -e TWINE_USERNAME=$PYPI_USERNAME -e TWINE_PASSWORD=$PYPI_PASSWORD -e TWINE_SERVER=$PYPI_SERVER $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/