notifications:
  email: false

jobs:
  include:
    - name: manylinux2014_x86_64
      language: ruby
      os: linux
      dist: xenial
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - bash run-docker.sh
    - name: manylinux2014_i686
      language: ruby
      os: linux
      dist: xenial
      services:
        - docker
      env:
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686
        - PRE_CMD=linux32
        - TYPE=docker
      install:
        - docker pull $DOCKER_IMAGE
      script:
        - bash run-docker.sh
    - name: codecov
      os: linux
      dist: xenial
      compiler: gcc
      language: c
      env:
        - TYPE=codecov
      addons:
        apt:
          packages:
            - cmake
            - lcov
            - gfortran
      script:
        - bash travis/run-codecov.sh
